on:
  push:
    branches: main

jobs:
  compile-rankings:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::jsonlite
            any::tidyverse
            any::rvest

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Compile womens rankings
        run: Rscript -e 'source("compile rankings.R")'
