on:
  push:
    branches: main

jobs:
  compile-rankings:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Compile womens rankings
        run: Rscript -e 'source("compile rankings.R")'
